// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {BaseHook} from "@uniswap/hooks/base/BaseHook.sol";
import {Hooks} from "@uniswap/v4-core/src/libraries/Hooks.sol";
import {IPoolManager} from "@uniswap/v4-core/src/interfaces/IPoolManager.sol";
import {StateLibrary} from "@uniswap/v4-core/src/libraries/StateLibrary.sol";
import {BalanceDelta} from "@uniswap/v4-core/src/types/BalanceDelta.sol";
import {PoolId} from "@uniswap/v4-core/src/types/PoolId.sol";
import {PoolKey} from "@uniswap/v4-core/src/types/PoolKey.sol";
import {SwapParams} from "@uniswap/v4-core/src/types/PoolOperation.sol";

import {IVolatusHook} from "./interfaces/IVolatusHook.sol";
import {EpochCursor} from "./libraries/EpochCursor.sol";
import {VarianceMath} from "./libraries/VarianceMath.sol";

/// @title VolatusHook
/// @notice Turns any Uniswap v4 pool into a realized-variance index of itself.
///
/// @dev The measurement has to happen where the risk is borne. A volatility index built on an
///      external feed is a different product with an oracle trust assumption; this one is
///      generated by the pool whose LPs it exists to protect, from the pool's own price path,
///      by the contract that already sees every price change.
///
///      The hot path is `_afterSwap` and it does one of two things:
///
///        - this block was already sampled: read one slot, return. Zero marginal cost to every
///          swap after the first in a block.
///        - first swap of the block: read the tick, clamp the delta, square it into the
///          accumulator, write the cursor. Two storage slots touched.
///
///      Nothing else happens on the swap path. Turning the accumulator into a variance, a
///      volatility or a settlement price is a `view` that runs at read time and costs traders
///      nothing.
///
///      **Epoch boundaries.** The accumulator is append-only and never reset, so an epoch is
///      the difference between two readings of it. The start reading is trivial — the vault
///      takes it when it opens the epoch. The end reading is not: the accumulator keeps growing
///      after an epoch closes, so a settlement that simply reads it later would fold post-epoch
///      volatility into the payoff and make settlement *timing* strategic for whichever side is
///      winning. So the vault registers the boundary in advance and the pool's own first swap
///      at or after it freezes the value. Nobody chooses that moment.
///
///      This is the one place the hook knows epochs exist, and it is deliberately the smallest
///      possible amount of knowing: a single `uint48` that rides in spare bits of a slot the
///      sampling gate already loads, so the check costs no extra SLOAD.
///
///      **Trust surface.** Only `vault` may register a boundary, because a permissionless
///      registry is a denial-of-service: anyone could register an earlier boundary, consume the
///      pending slot, and leave the real epoch permanently unsettleable. `vault` is set exactly
///      once, by `vaultSetter`, and can never be changed afterwards — see `setVault`.
///
///      Security posture, against `v4-security-foundations`:
///        - `afterSwap` only (MEDIUM). No `beforeSwap`, so the hook cannot touch pricing.
///        - No return-delta permissions at all, so the NoOp rug-pull vector does not exist
///          here and the hook never participates in delta accounting.
///        - `onlyPoolManager` is enforced by `BaseHook` on every callback.
///        - No external calls, no loops, no upgrade path, no token custody. The hook holds
///          nothing an attacker could want.
///        - One privileged action exists — `setVault`, callable once by `vaultSetter` — and it
///          cannot mint, move, or freeze anything. Its whole power is nominating who may ask
///          for a boundary snapshot.
///        - `sender` is deliberately unused: this hook observes the pool, not the trader, so
///          router identity is irrelevant to it.
contract VolatusHook is BaseHook, IVolatusHook {
    using EpochCursor for EpochCursor.VarianceState;
    using StateLibrary for IPoolManager;

    /// @notice Largest tick move a single observation may contribute.
    /// @dev ~10.5% of price in one block. A one-block dislocation — a large legitimate trade,
    ///      a flash-loan spike, a thin-book sweep — is therefore bounded in what it can add to
    ///      an epoch, while ordinary volatility passes through untouched. Immutable, because a
    ///      settable clamp would be a governance lever over a number that settles money.
    int256 public constant MAX_TICK_DELTA = 1000;

    /// @dev Per-pool sampling state. Keyed by PoolId, so one deployment serves every pool that
    ///      points at this hook.
    mapping(PoolId => EpochCursor.VarianceState) internal _state;

    /// @dev Accumulator frozen at each requested boundary: poolId -> block -> value **plus
    ///      one**. The offset lets zero mean "never recorded" while still allowing a legitimate
    ///      frozen value of zero, which a pool that never moved genuinely produces. The
    ///      alternative — a parallel bool mapping — costs a second cold SSTORE on the crossing
    ///      block, and that block is paid for by whichever swapper happens to cross the
    ///      boundary. They did not ask to fund it, so it is worth the +1.
    ///      `MAX_ACCUMULATOR` is ~1e58, so the increment cannot overflow.
    mapping(PoolId => mapping(uint48 => uint256)) internal _snapshotPlusOne;

    /// @notice The only address permitted to call `setVault`. Fixed at construction.
    /// @dev An explicit constructor argument rather than `msg.sender`, because a v4 hook has to
    ///      be deployed through the deterministic CREATE2 factory for its address to encode its
    ///      permissions — which makes `msg.sender` in this constructor the factory at
    ///      `0x4e59…4956C`, not the deploying account. Taking it from `msg.sender` compiles,
    ///      passes every test that deploys the hook directly, and then bricks `setVault`
    ///      permanently on the first real deployment.
    address public immutable vaultSetter;

    /// @notice The only address permitted to request epoch boundaries. Set once, then frozen.
    address public vault;

    error NotVaultSetter();
    error VaultAlreadySet();
    error InvalidVault();
    error NotVault();
    error SnapshotInPast(uint48 atBlock, uint256 currentBlock);
    error SnapshotAlreadyPending(uint48 pending);

    constructor(IPoolManager _poolManager, address vaultSetter_) BaseHook(_poolManager) {
        if (vaultSetter_ == address(0)) revert InvalidVault();
        vaultSetter = vaultSetter_;
    }

    /// @notice Nominates the vault permitted to register epoch boundaries.
    /// @dev Deliberately a one-shot call restricted to `vaultSetter` rather than an owner role.
    ///      It exists
    ///      because the hook and the vault each need the other's address, which no constructor
    ///      ordering can satisfy. Once set it can never change, so the hook has no standing
    ///      administrator.
    function setVault(address vault_) external {
        if (msg.sender != vaultSetter) revert NotVaultSetter();
        if (vault != address(0)) revert VaultAlreadySet();
        if (vault_ == address(0)) revert InvalidVault();

        vault = vault_;
        emit VaultSet(vault_);
    }

    /// @inheritdoc IVolatusHook
    /// @dev Rejects a second pending boundary rather than overwriting one, so an epoch that has
    ///      not yet been frozen cannot be silently orphaned.
    function requestSnapshot(PoolId id, uint48 atBlock) external {
        if (msg.sender != vault) revert NotVault();
        if (atBlock <= block.number) revert SnapshotInPast(atBlock, block.number);

        uint48 pending = _state[id].pendingSnapshot;
        if (pending != 0) revert SnapshotAlreadyPending(pending);

        _state[id].pendingSnapshot = atBlock;
        emit SnapshotRequested(id, atBlock);
    }

    /// @inheritdoc IVolatusHook
    /// @dev Called by the vault when an epoch settles.
    ///
    ///      Without this a pool could be left unable to host another epoch. An epoch whose
    ///      boundary passes with no further trading never fires its snapshot — settlement
    ///      correctly falls back to the live accumulator, which is exact in that case — but the
    ///      pending slot stays occupied, and `requestSnapshot` refuses to overwrite it. The pool
    ///      would then be blocked until somebody happened to swap on it.
    ///
    ///      Safe to call unconditionally: after settlement the epoch's payoff is frozen and its
    ///      boundary is no longer needed by anyone. A snapshot that already fired left the slot
    ///      at zero, so this is a no-op in that case.
    function releaseSnapshot(PoolId id) external {
        if (msg.sender != vault) revert NotVault();

        uint48 pending = _state[id].pendingSnapshot;
        if (pending != 0) {
            _state[id].pendingSnapshot = 0;
            emit SnapshotReleased(id, pending);
        }
    }

    /// @inheritdoc BaseHook
    function getHookPermissions() public pure override returns (Hooks.Permissions memory) {
        return Hooks.Permissions({
            beforeInitialize: false,
            afterInitialize: true, // seed the cursor at the pool's opening tick
            beforeAddLiquidity: false,
            afterAddLiquidity: false,
            beforeRemoveLiquidity: false,
            afterRemoveLiquidity: false,
            beforeSwap: false,
            afterSwap: true, // the accumulator
            beforeDonate: false,
            afterDonate: false,
            beforeSwapReturnDelta: false,
            afterSwapReturnDelta: false,
            afterAddLiquidityReturnDelta: false,
            afterRemoveLiquidityReturnDelta: false
        });
    }

    // -------------------------------------------------------------------------
    // Hook callbacks
    // -------------------------------------------------------------------------

    /// @dev Seeds the cursor so the pool's first swap has a predecessor to difference against.
    ///      Without this the opening move would be silently dropped.
    function _afterInitialize(address, PoolKey calldata key, uint160, int24 tick) internal override returns (bytes4) {
        PoolId id = key.toId();
        _state[id].observe(tick, MAX_TICK_DELTA);

        emit PoolTracked(id, tick);
        return BaseHook.afterInitialize.selector;
    }

    /// @dev The hot path. See the contract-level comment for the cost argument.
    function _afterSwap(address, PoolKey calldata key, SwapParams calldata, BalanceDelta, bytes calldata)
        internal
        override
        returns (bytes4, int128)
    {
        PoolId id = key.toId();
        EpochCursor.VarianceState storage s = _state[id];

        // Check the gate before reading the pool. `observe` would reject a second sample in
        // the same block anyway, but bailing here also skips the `getSlot0` call, which is the
        // expensive half of this path.
        if (s.isSampled()) return (BaseHook.afterSwap.selector, 0);

        // Freeze the epoch boundary *before* this observation is applied. Movement during the
        // crossing block therefore belongs to the next epoch, not the one settling. That is a
        // deterministic slight undercount, chosen over a number an attacker could aim at by
        // timing a swap. `pendingSnapshot` shares a slot with the gate above, so reading it
        // here costs nothing.
        uint48 pending = s.pendingSnapshot;
        if (pending != 0 && block.number >= pending) {
            _snapshotPlusOne[id][pending] = s.accumulator + 1;
            s.pendingSnapshot = 0;

            emit SnapshotTaken(id, pending, s.accumulator);
        }

        (, int24 tick,,) = poolManager.getSlot0(id);

        if (s.observe(tick, MAX_TICK_DELTA)) {
            emit VarianceObserved(id, tick, s.accumulator, s.observations);
        }

        return (BaseHook.afterSwap.selector, 0);
    }

    // -------------------------------------------------------------------------
    // Views — the read side, off the swap path
    // -------------------------------------------------------------------------

    /// @inheritdoc IVolatusHook
    function varianceState(PoolId id) external view returns (EpochCursor.VarianceState memory) {
        return _state[id];
    }

    /// @inheritdoc IVolatusHook
    function accumulator(PoolId id) external view returns (uint256) {
        return _state[id].accumulator;
    }

    /// @inheritdoc IVolatusHook
    function observations(PoolId id) external view returns (uint32) {
        return _state[id].observations;
    }

    /// @inheritdoc IVolatusHook
    function lastObservedBlock(PoolId id) external view returns (uint48) {
        return _state[id].lastBlock;
    }

    /// @inheritdoc IVolatusHook
    function snapshotAt(PoolId id, uint48 atBlock) external view returns (bool, uint256) {
        uint256 stored = _snapshotPlusOne[id][atBlock];
        return stored == 0 ? (false, 0) : (true, stored - 1);
    }

    /// @notice The boundary this pool is waiting on, or zero if none.
    function pendingSnapshot(PoolId id) external view returns (uint48) {
        return _state[id].pendingSnapshot;
    }

    /// @inheritdoc IVolatusHook
    function varianceBetween(uint256 startAccumulator, uint256 endAccumulator) public pure returns (uint256) {
        // The accumulator only ever grows, so an inverted pair is a caller error rather than
        // something to saturate away quietly.
        return VarianceMath.realizedVariance(endAccumulator - startAccumulator);
    }

    /// @inheritdoc IVolatusHook
    function realizedVolatility(uint256 startAccumulator, uint256 endAccumulator, uint256 elapsedSeconds)
        external
        pure
        returns (uint256)
    {
        return VarianceMath.volatilityFromAccumulator(endAccumulator - startAccumulator, elapsedSeconds);
    }
}
